# Estágio 1: Configurando o ambiente de desenvolvimento Django
FROM python:3.9 AS django-backend

ARG postgres_host=''

ENV PYTHONUNBUFFERED=1
ENV POSTGRES_HOST ${postgres_host}

RUN echo "starting build"

# Define o diretório de trabalho para o serviço backend
WORKDIR /service

# Copia os arquivos de dependências do Django
COPY requirements.txt .

RUN set -ex \
    && apt-get update \
    && apt-get install -y unzip curl netcat-openbsd \
    && pip --version \
    && python --version \
    && pip install --upgrade pip \
    && pip install --no-cache-dir gunicorn \
    && pip --version \
    && python --version \
    && pip install --no-cache-dir -r requirements.txt \
    && rm -rf /var/lib/apt/list/* \
    && rm -rf /root/.cache \
    && find / -name "*.pyc" -exec rm -f {} \;

 
# Copia o código fonte do Django
COPY . .

# Expõe a porta 8000 para o servidor Django
EXPOSE 80

ENTRYPOINT [ "/service/entrypoint.sh" ]